// <auto-generated />
using System;
using CRIOLLOPABLO_EXAMANE_PGR1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRIOLLOPABLO_EXAMANE_PGR1.Migrations
{
    [DbContext(typeof(CRIOLLOPABLO_EXAMANE_PGR1Context))]
    partial class CRIOLLOPABLO_EXAMANE_PGR1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRIOLLOPABLO_EXAMANE_PGR1.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("CRIOLLOPABLO_EXAMANE_PGR1.Models.PCriollo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCelular")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("celularId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("celularId");

                    b.ToTable("PCriollo");
                });

            modelBuilder.Entity("CRIOLLOPABLO_EXAMANE_PGR1.Models.PCriollo", b =>
                {
                    b.HasOne("CRIOLLOPABLO_EXAMANE_PGR1.Models.Celular", "celular")
                        .WithMany()
                        .HasForeignKey("celularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("celular");
                });
#pragma warning restore 612, 618
        }
    }
}
